apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: spring-boot-cicd
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: "master"
    - name: image-url
      type: string
  tasks:
    - name: fetch-repository
      taskRef:
        name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-push-image
      taskRef:
        name: build-push-image
      params:
        - name: image-url
          value: $(params.image-url)
      workspaces:
        - name: source
          workspace: shared-workspace
