apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: spring-boot-cicd-pipeline
spec:
  params:
    - name: git-repo-url
      type: string
      description: URL of the git repo for the source code.
    - name: git-repo-revision
      type: string
      description: Git revision to checkout.
    - name: image-name
      type: string
      description: Full URL location to push the resulting image to.
  workspaces:
    - name: shared-workspace
      description: The workspace that will be shared among tasks.
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: $(params.git-repo-revision)
    - name: build-push-image
      taskRef:
        name: build-push-image
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.image-name)
