apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-repository
spec:
  workspaces:
    - name: output
  params:
    - name: url
      type: string
      description: The git repository URL
    - name: revision
      type: string
      description: The git revision
      default: "master"
  steps:
    - name: clone
      image: alpine/git:latest
      script: |
        #!/usr/bin/env sh
        git clone $(params.url) /workspace/output
        cd /workspace/output
        git checkout $(params.revision)
